force-app/main/default/objects/custom_setting_list__c/custom_setting_list__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>custom setting list</label>
</CustomObject>

force-app/main/default/objects/custom_setting_list__c/fields/country_code__c.field-meta.xml
<CustomField>
    <fullName>country_code__c</fullName>
    <label>country code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VFCountryCode_CX.cls
public with sharing class VFCountryCode_CX {
    public String selectedCountry {get; set;}
        public String countryCode {get; set;}

    public VFCountryCode_CX(ApexPages.StandardController controller) {

    }

    public List<SelectOption> getCountriesOptions() {
        List<SelectOption> countryOptions = new List<SelectOption>();
        
        Map<String, custom_setting_list__c> countryCodeMap = custom_setting_list__c.getAll();
        
        countryOptions.add(new SelectOption('','--None--'));
        
       for(String countryName: countryCodeMap.keySet()){
          String cLabel =countryName;
          String value= countryCodeMap.get(countryName).country_code__c;
           
            countryOptions.add(new SelectOption(value,cLabel )); //1.Value, 2.Lable
        }

        
       
        
 
        return countryOptions;
    }
    

}