force-app/main/default/objects/address__c/address__c.object-meta.xml
<CustomObject>
    <label>address</label>
    <nameField>
        <displayFormat>ADRID-{00000000}</displayFormat>
        <label>address id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/address__c/fields/applicant__c.field-meta.xml
<CustomField>
    <fullName>applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>applicant</label>
    <referenceTo>applicant__c</referenceTo>
    <relationshipLabel>address</relationshipLabel>
    <relationshipName>address_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/address__c/fields/city__c.field-meta.xml
<CustomField>
    <fullName>city__c</fullName>
    <label>city</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Ahmedabad</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Kolkata</fullName>
            </value>
            <value>
                <fullName>Surat</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Jaipur</fullName>
            </value>
            <value>
                <fullName>Lucknow</fullName>
            </value>
            <value>
                <fullName>Kanpur</fullName>
            </value>
            <value>
                <fullName>Nagpur</fullName>
            </value>
            <value>
                <fullName>sindh</fullName>
            </value>
            <value>
                <fullName>madras</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/address__c/fields/state__c.field-meta.xml
<CustomField>
    <fullName>state__c</fullName>
    <label>state</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>state</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/applicant__c/applicant__c.object-meta.xml
<CustomObject>
    <label>applicant</label>
    <nameField>
        <displayFormat>APID-{0000}</displayFormat>
        <label>applicant  ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>applicants</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/AddressProvider.cls
public with sharing class AddressProvider {

    
   @AuraEnabled
   public static List<address__c> serchAddresMethod (string applicantId){
    try {

        ID aaapid=[select id ,Name from applicant__c where Name =: applicantId].id;
        
        return  [select Name,state__c,city__c from address__c where applicant__c =:aaapid];
   
} catch (Exception e) {
        throw new AuraHandledException(e.getMessage());
    }
   }
}