force-app/main/default/objects/address__c/address__c.object-meta.xml
<CustomObject>
    <label>address</label>
    <nameField>
        <displayFormat>ADRID-{00000000}</displayFormat>
        <label>address id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/address__c/fields/applicant__c.field-meta.xml
<CustomField>
    <fullName>applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>applicant</label>
    <referenceTo>applicant__c</referenceTo>
    <relationshipLabel>address</relationshipLabel>
    <relationshipName>address_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/address__c/fields/city__c.field-meta.xml
<CustomField>
    <fullName>city__c</fullName>
    <label>city</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Ahmedabad</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Kolkata</fullName>
            </value>
            <value>
                <fullName>Surat</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Jaipur</fullName>
            </value>
            <value>
                <fullName>Lucknow</fullName>
            </value>
            <value>
                <fullName>Kanpur</fullName>
            </value>
            <value>
                <fullName>Nagpur</fullName>
            </value>
            <value>
                <fullName>sindh</fullName>
            </value>
            <value>
                <fullName>madras</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/address__c/fields/pin_code__c.field-meta.xml
<CustomField>
    <fullName>pin_code__c</fullName>
    <label>pin code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/applicant__c/applicant__c.object-meta.xml
<CustomObject>
    <label>applicant</label>
    <nameField>
        <displayFormat>APID-{0000}</displayFormat>
        <label>applicant  ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>applicants</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/applicant__c/fields/ListOfAddresses__c.field-meta.xml
<CustomField>
    <fullName>ListOfAddresses__c</fullName>
    <label>ListOfAddresses</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/applicant__c/fields/police_varification__c.field-meta.xml
<CustomField>
    <fullName>police_varification__c</fullName>
    <defaultValue>true</defaultValue>
    <label>police varification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchAddressToApplicant.cls
global class BatchAddressToApplicant implements Database.Batchable<sobject> {
    
    global Database.QueryLocator start(Database.BatchableContext BC){
     return Database.getQueryLocator('select id,Name,city__c,pin_code__c,applicant__r.id,applicant__r.ListOfAddresses__c,applicant__r.police_varification__c,applicant__r.Name from address__c where city__c=\'Nagpur\' and pin_code__c like\'44%\' and applicant__r.police_varification__c=true');   
    }
    global void execute(Database.BatchableContext BC,list<address__c>addlist){
        set<id>appsetid=new set<id>();
        for(address__c objadd:addlist){
            if(objadd.applicant__c!=null){
              appsetid.add(objadd.applicant__c);  
            }
        }
        
        map<id,applicant__c> appmap=new map<id,applicant__c>();
        if(!appsetid.isEmpty()){
            for(applicant__c objapp:[select id,Name,ListOfAddresses__c,police_varification__c from applicant__c where id IN:appsetid]){
               appmap.put(objapp.id,objapp); 
            }
            if(!appmap.isEmpty()){
                for(address__c objadd:addlist){
                    if(appmap.containskey(objadd.applicant__c)){
                        
                        
                    }
                }
            }
        }
        
    }
    global void finish(Database.BatchableContext BC){
        
    }
}