force-app/main/default/objects/address__c/address__c.object-meta.xml
<CustomObject>
    <label>address</label>
    <nameField>
        <displayFormat>ADRID-{00000000}</displayFormat>
        <label>address id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/address__c/fields/applicant__c.field-meta.xml
<CustomField>
    <fullName>applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>applicant</label>
    <referenceTo>applicant__c</referenceTo>
    <relationshipLabel>address</relationshipLabel>
    <relationshipName>address_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/address__c/fields/city__c.field-meta.xml
<CustomField>
    <fullName>city__c</fullName>
    <label>city</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Ahmedabad</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Kolkata</fullName>
            </value>
            <value>
                <fullName>Surat</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Jaipur</fullName>
            </value>
            <value>
                <fullName>Lucknow</fullName>
            </value>
            <value>
                <fullName>Kanpur</fullName>
            </value>
            <value>
                <fullName>Nagpur</fullName>
            </value>
            <value>
                <fullName>sindh</fullName>
            </value>
            <value>
                <fullName>madras</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/applicant__c/applicant__c.object-meta.xml
<CustomObject>
    <label>applicant</label>
    <nameField>
        <displayFormat>APID-{0000}</displayFormat>
        <label>applicant  ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>applicants</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/applicant__c/fields/gender__c.field-meta.xml
<CustomField>
    <fullName>gender__c</fullName>
    <description>this is used to different gender</description>
    <inlineHelpText>enter proper gender like male ,female t,ransgender</inlineHelpText>
    <label>gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>male</fullName>
            </value>
            <value>
                <fullName>female</fullName>
            </value>
            <value>
                <fullName>transgender</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/applicant__c/fields/police_varification__c.field-meta.xml
<CustomField>
    <fullName>police_varification__c</fullName>
    <defaultValue>true</defaultValue>
    <label>police varification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchAddresCityUpdate.cls
global class BatchAddresCityUpdate implements Database.Batchable<sObject>{
    
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return  Database.getQueryLocator('select city__c,applicant__r.police_varification__c,applicant__r.gender__c from address__c where applicant__r.police_varification__c=true and city__c!=\'Pune\' and applicant__r.gender__c=\'male\'');
        
    }
    
    global void execute(Database.BatchableContext BC,list<address__c>addlist){
        if(!addlist.isempty()){
            for(address__c objadd:addlist){
             
                objadd.city__c='Pune';
                 
                
            }
            database.update(addlist,false);
        }
        
    }
    
    global  void finish(Database.BatchableContext BC){
        
    }

}