force-app/main/default/objects/applicant__c/applicant__c.object-meta.xml
<CustomObject>
    <label>applicant</label>
    <nameField>
        <displayFormat>APID-{0000}</displayFormat>
        <label>applicant  ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>applicants</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/applicant__c/fields/first_name__c.field-meta.xml
<CustomField>
    <fullName>first_name__c</fullName>
    <label>first name</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/applicant__c/fields/last_name__c.field-meta.xml
<CustomField>
    <fullName>last_name__c</fullName>
    <label>last name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/applicantprovider.cls
public with Sharing class applicantprovider {
    @AuraEnabled
   public static List<applicant__c> sarchApplicantNameWise(applicant__c objapp){
    try {
       if(string.isNotEmpty(objapp.first_name__c)){
        return[select Name,first_name__c,last_name__c from applicant__c where first_name__c like:objapp.first_name__c+'%'];
       
    }
        else{
            return null;
        }
    } catch (Exception e) {
        throw new AuraHandledException(e.getMessage());
    }
   }
 @AuraEnabled
 public static list<applicant__c> deleteSelectedApplicantRecords(List<id>appDlist,applicant__c objApp){
    try {
        database.delete([select id from applicant__c where id IN:appDlist],false);
         return[select Name,first_name__c,last_name__c from applicant__c where first_name__c like:objapp.first_name__c+'%'];
    } catch (Exception e) {
        throw new AuraHandledException(e.getMessage());
    }
 }
 
}