force-app/main/default/objects/applicant__c/applicant__c.object-meta.xml
<CustomObject>
    <label>applicant</label>
    <nameField>
        <displayFormat>APID-{0000}</displayFormat>
        <label>applicant  ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>applicants</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/applicant__c/fields/gender__c.field-meta.xml
<CustomField>
    <fullName>gender__c</fullName>
    <description>this is used to different gender</description>
    <inlineHelpText>enter proper gender like male ,female t,ransgender</inlineHelpText>
    <label>gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>male</fullName>
            </value>
            <value>
                <fullName>female</fullName>
            </value>
            <value>
                <fullName>transgender</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/applicant__c/fields/police_varification__c.field-meta.xml
<CustomField>
    <fullName>police_varification__c</fullName>
    <defaultValue>true</defaultValue>
    <label>police varification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/applicant__c/fields/special_Mark_on_Body__c.field-meta.xml
<CustomField>
    <fullName>special_Mark_on_Body__c</fullName>
    <label>special Mark on Body</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchApplicantPolmark.cls
global class BatchApplicantPolmark implements Database.Batchable<sObject> {
    
    global  Database.QueryLocator start( Database.BatchableContext BC){
        string query='select ID,gender__c,police_varification__c,special_Mark_on_Body__c from applicant__c where gender__c!=\'transgender\' ';
        return Database.getQueryLocator(query);
    }
    global void execute( Database.Batchablecontext BC, List<applicant__c> applist){
        if(!applist.isEmpty()){
            for(applicant__c objapp:applist){
                if(objapp.gender__c=='male'&& !objapp.police_varification__c){
                    objapp.police_varification__c=true;
                    objapp.special_Mark_on_Body__c='Yahoo';
                }
                else
                if(objapp.gender__c=='female'&& objapp.police_varification__c){
                    objapp.police_varification__c=false;
                    objapp.special_Mark_on_Body__c='Google';
                }
            }
                
            Database.update(applist,false);
        }
            
        
        
        
    }    
    
    global void finish( Database.Batchablecontext BC){
        
        
    } 

}