force-app/main/default/objects/applicant__c/applicant__c.object-meta.xml
<CustomObject>
    <label>applicant</label>
    <nameField>
        <displayFormat>APID-{0000}</displayFormat>
        <label>applicant  ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>applicants</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/applicant__c/fields/first_name__c.field-meta.xml
<CustomField>
    <fullName>first_name__c</fullName>
    <label>first name</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/applicant__c/fields/gender__c.field-meta.xml
<CustomField>
    <fullName>gender__c</fullName>
    <description>this is used to different gender</description>
    <inlineHelpText>enter proper gender like male ,female t,ransgender</inlineHelpText>
    <label>gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>male</fullName>
            </value>
            <value>
                <fullName>female</fullName>
            </value>
            <value>
                <fullName>transgender</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/applicant__c/fields/last_name__c.field-meta.xml
<CustomField>
    <fullName>last_name__c</fullName>
    <label>last name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SearchApplicantProvider.cls
public with sharing class SearchApplicantProvider {
    @AuraEnabled
    public static applicant__c SearchApplicantProvider(applicant__c objapp){
        try {
            return [select id,first_name__c,last_name__c,gender__c from applicant__c where Name=:objapp.Name];   
              
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
   
   
}