force-app/main/default/objects/applicant__c/applicant__c.object-meta.xml
<CustomObject>
    <label>applicant</label>
    <nameField>
        <displayFormat>APID-{0000}</displayFormat>
        <label>applicant  ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>applicants</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/applicant__c/fields/first_name__c.field-meta.xml
<CustomField>
    <fullName>first_name__c</fullName>
    <label>first name</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/applicant__c/fields/gender__c.field-meta.xml
<CustomField>
    <fullName>gender__c</fullName>
    <description>this is used to different gender</description>
    <inlineHelpText>enter proper gender like male ,female t,ransgender</inlineHelpText>
    <label>gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>male</fullName>
            </value>
            <value>
                <fullName>female</fullName>
            </value>
            <value>
                <fullName>transgender</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/applicant__c/fields/last_name__c.field-meta.xml
<CustomField>
    <fullName>last_name__c</fullName>
    <label>last name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/applicant__c/fields/mobile_no__c.field-meta.xml
<CustomField>
    <fullName>mobile_no__c</fullName>
    <label>mobile no</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/applicant__c/fields/police_varification__c.field-meta.xml
<CustomField>
    <fullName>police_varification__c</fullName>
    <defaultValue>true</defaultValue>
    <label>police varification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchApplicantPoliceVerification_Test.cls
@isTest
public class BatchApplicantPoliceVerification_Test {
    @testsetup
    public static void testSetupMethod(){
       list<applicant__c> applist=new list<applicant__c>();
        for(integer i=1; i<=200;i++){
            applicant__c objacc=new applicant__c(first_name__c='kishor +i',last_name__c='bhai +i',mobile_no__c='1111111111',gender__c='male');

         applist.add(objacc);
            
            
            
        }
         if(!applist.isEmpty())
        		Database.insert(applist,false);

     
    }

    @isTest
    public static void testBatchApplicantPoliceUpdatec(){  
        test.startTest();
        Database.executeBatch(new BatchApplicantPoliceUpdateT(),200);
        test.stopTest();
        List<applicant__c> actualAppList =  [select id, gender__c, police_varification__c from applicant__c where police_varification__c=true]; //200
         System.assertEquals(200, actualAppList.size());

        
       
      
    }
}