force-app/main/default/objects/applicant__c/applicant__c.object-meta.xml
<CustomObject>
    <label>applicant</label>
    <nameField>
        <displayFormat>APID-{0000}</displayFormat>
        <label>applicant  ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>applicants</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/applicant__c/fields/gender__c.field-meta.xml
<CustomField>
    <fullName>gender__c</fullName>
    <description>this is used to different gender</description>
    <inlineHelpText>enter proper gender like male ,female t,ransgender</inlineHelpText>
    <label>gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>male</fullName>
            </value>
            <value>
                <fullName>female</fullName>
            </value>
            <value>
                <fullName>transgender</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/applicant__c/fields/police_varification__c.field-meta.xml
<CustomField>
    <fullName>police_varification__c</fullName>
    <defaultValue>true</defaultValue>
    <label>police varification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchApplicantPoliceVerification.cls
global class BatchApplicantPoliceVerification implements Database.Batchable<sObject> {
      
    global Database.QueryLocator start(Database.BatchableContext BC){
    return Database.getQueryLocator('select id,Name,gender__c,police_varification__c from applicant__c where gender__c=\'male\' and police_varification__c=false');    
    }
    global void execute(Database.BatchableContext BC,list<applicant__c>applist){
        if(!applist.isEmpty()){
            for(applicant__c objapp:applist){
                if(string.isNotBlank(objapp.gender__c)){
                   objapp.police_varification__c=true;
                }
            }
            Database.update(applist,false);
        }
    }
    
    global void finish(Database.BatchableContext BC){
       
        
    }
        
    
}